GXX = cl.exe
CFLAGS = /W3 /O2 /EHsc /MD /D "NDEBUG" /D "WIN32" /nologo /fp:precise /Zc:wchar_t /Zc:forScope
LDFLAGS = /INCREMENTAL:NO /SUBSYSTEM:CONSOLE

all: svm.obj svmtools.obj test_grid.exe

%.obj: %.cpp
	@echo to build $@
	@$(CXX) $(CFLAGS) $<

test_grid.exe: test_grid.obj svmtools.obj
	@echo to build test_grid.exe
	@link.exe $(LDFLAGS) test_grid.obj svmtools.obj /OUT:test_grid.exe

